# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.
# This workflow will build a Java project with Gradle and cache/restore any dependencies to improve the workflow execution time
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: Java CI with Gradle

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4
        with:
          submodules: recursive

      - name: Set up JDK 11
        uses: actions/setup-java@v1
        with:
          java-version: 11
          distribution: 'zulu'

      - name: Set execution right for gradlew
        run: chmod +x gradlew

      - name: Build with BAS from ${{ github.reff }} branch
        run: |
          ./gradlew \
          -Pbuild.number=$GITHUB_RUN_NUMBER \
          clean build \
          --info \
          --stacktrace \
          --refresh-dependencies \
          --profile
