name: Docker Image CI

on:
  workflow_dispatch:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
        
#    - name: Log into registry
#      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin
      
    - name: Set up JDK
      uses: actions/setup-java@v2
      with:
        java-version: 17
        distribution: 'zulu'
  
    - name: Set execution right for gradlew
      run: chmod +x gradlew
  
    - name: Build with Gradle from ${{ github.reff }} branch
      run: |
          ./gradlew \
          -Pbuild.number=${{ github.run_number }} \
          -Pgithub.actor=${{ github.actor }} \
          -Pgithub.token=${{ secrets.GITHUB_TOKEN }} \
          -Pgithub.package.name=ghcr.io/${{ github.repository }} \
          -Pgithub.package.version=latest \
          clean build bootBuildImage \
          --info \
          --stacktrace \
          --refresh-dependencies \
          --profile
  
#    - name: Publish package
#      run: docker push ghcr.io/${{ github.repository }}:latest
